Repository MarkCodable/MarkCodable, pull requests merged in 2022-09, with the labels that each got.

#16 Swift 5.6 support
  Package.swift
  Sources/MarkCodable/Decoder/MarkKeyedDecoding.swift
  Sources/MarkCodable/Encoder/MarkEncoder.swift
  Sources/MarkCodable/MarkCodable.swift
Labels: enhancement

#30 Package.swift improvements
  Package.swift
Labels: documentation

#28 Fix sample app: nested paths during decoding, supporting optional values
  Sources/MarkCodable/Decoder/MarkKeyedDecoding.swift
  Sources/MarkCodable/Encoder/MarkKeyedEncoding.swift
  Sources/MarkTestApp/main.swift
  Tests/MarkCodableTests/MarkCoderTests.swift
  Tests/MarkCodableTests/Utility/TestData.swift
  Tests/MarkCodableTests/Utility/TestModels.swift
Labels: bug
